### ISSUE TITLE
Too many dependencies

### ISSUE THREAD

**Issue by kirksw** [flink-extended/flink-scala-api#178]
Was shocked to find my dependencyTree output became 46,993 lines long after adding this library as a dependency, a large many of these lines were from packages from `com.vladsch.flexmark`. I also found your sandbox repo and saw you reduced this down further, basically excluding 99% of the original packages.

Maybe this should be looked at in an upcoming release? Or perhaps better document how to use this in production.

```
"org.flinkextended" %% "flink-scala-api" % s"${flinkVersion}_${flinkXVersion}" excludeAll(
    ExclusionRule(organization = "com.vladsch.flexmark"),
    ExclusionRule(organization = "org.apache.flink"),
    ExclusionRule(organization = "org.scalameta"),
    ExclusionRule(organization = "com.google.code.findbugs"),
  ),
```

**Comment by novakov-alexey** [comment]
Thanks for the ticket. 

This also affects SBT `assembly` build of the user JAR file. I guess these 3 exclusion due to the Mdoc SBT plugin. I do not understand so far why it adds its dependencies the user project as well.

ExclusionRule(organization = "com.vladsch.flexmark"),
ExclusionRule(organization = "org.scalameta"),
ExclusionRule(organization = "com.google.code.findbugs")

As for Flink dependencies itself:

```scala
"org.apache.flink"  % "flink-streaming-java" % flinkVersion,
"org.apache.flink"  % "flink-java"           % flinkVersion,
```

they probably need to be moved it to the `Provided` scope.

**Comment by novakov-alexey** [comment]
@kirksw newly released version should not require jar exclusions any more. Can you try it with your fat JAR build?

**Comment by kirksw** [comment]
> @kirksw newly released version should not require jar exclusions any more. Can you try it with your fat JAR build?

Hi @novakov-alexey, I can confirm this PR resolves the need to include exclusions, appreciate the quick work :)

**Comment by novakov-alexey** [comment]
Ok, great. Thanks for quick confirmation. @kirksw
